name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, sqlite3, gd, zip
        coverage: none

    - name: Copy .env.testing
      run: |
        rm -f .env.testing
        touch .env.testing
        echo "APP_ENV=testing" >> .env.testing
        echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> .env.testing
        echo "DB_CONNECTION=sqlite" >> .env.testing
        echo "DB_DATABASE=\"database/database.sqlite\"" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing

    - name: Prepare sqlite database file
      run: |
        mkdir -p database
        php -r 'file_exists("database/database.sqlite") || touch("database/database.sqlite");'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-interaction --prefer-dist --optimize-autoloader
        else
          echo "composer.json not found; skipping composer install."
        fi
      working-directory: ${{ github.workspace }}

    - name: Directory Permissions
      run: |
        if [ -d storage ]; then chmod -R 777 storage; fi
        if [ -d bootstrap/cache ]; then chmod -R 777 bootstrap/cache; fi

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      id: run-tests
      run: |
        EXIT_CODE=0
        if [ -f vendor/bin/phpunit ]; then
          vendor/bin/phpunit --colors=never --log-junit junit.xml | tee phpunit.out || EXIT_CODE=$?
        else
          echo "PHPUnit not found; attempting artisan test" | tee phpunit.out
          php artisan test --colors=never | tee -a phpunit.out || EXIT_CODE=$?
        fi
        echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          junit.xml
          phpunit.out
          storage/logs/
          bootstrap/cache/
        retention-days: 3

    - name: Fail if tests failed
      if: steps.run-tests.outputs.exit_code != '0'
      run: exit 1